#server:
#  port: 80
#spring:
#  application:
#    name: mall-gateway
#  cloud:
#    nacos:
#      server-addr: 192.168.10.66:8848
#    gateway:
#      routes:
#        - id: product
#          uri: lb://mall-product
#          predicates:
#          - Path=/api/product/**
#          filters:
#          - RewritePath=/api/(?<segment>.*),/$\{segment}
#
#        - id: renren-admin
#          uri: lb://renren-fast
#          predicates:
#          - Path=/api/**
#          filters:
#          - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
