#server:
#  port: 10000
#spring:
#  datasource:
#    druid:
#      # MySQL
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://192.168.10.66:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
#      username: root
#      password: root
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 5000
#      # 状态监控
#      filter:
#        stat:
#          enabled: true
#          db-type: mysql
#          log-slow-sql: true
#          slow-sql-millis: 2000
#        # 监控过滤器
#      web-stat-filter:
#        enabled: true
#        exclusions:
#          - "*.js"
#          - "*.gif"
#          - "*.jpg"
#          - "*.png"
#          - "*.css"
#          - "*.ico"
#          - "/druid/*"
#      # druid监控页面
#      stat-view-servlet:
#        enabled: true
#        url-pattern: /druid/*
#        reset-enable: false
#        login-username: root
#        login-password: root
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto